# Step 1: Data Check — TCGA KIRC Project
This notebook loads the three data files and prints basic info to understand their structure.

In [1]:
# Import pandas — the main library for working with tabular data
import pandas as pd

In [2]:
# Load all three TSV files into pandas DataFrames
# sep='\t' tells pandas the columns are separated by tabs

clinical = pd.read_csv("../data/clinical.tsv", sep="\t")
follow_up = pd.read_csv("../data/follow_up.tsv", sep="\t")
expression = pd.read_csv("../data/kirc_expression.tsv", sep="\t")

print("Files loaded successfully!")

Files loaded successfully!

In [3]:
# Print the shape (rows, columns) of each dataframe
# This tells us how big each dataset is

print("clinical shape:   ", clinical.shape)
print("follow_up shape:  ", follow_up.shape)
print("expression shape: ", expression.shape)

clinical shape:    (1636, 210)
follow_up shape:   (3611, 198)
expression shape:  (20530, 607)

In [4]:
# Show first 5 rows of clinical data
print("=== Clinical Data (first 5 rows) ===")
clinical.head()

=== Clinical Data (first 5 rows) ===

,project.project_id,cases.case_id,cases.consent_type,cases.days_to_consent,cases.days_to_lost_to_followup,cases.disease_type,cases.index_date,cases.lost_to_followup,cases.primary_site,cases.submitter_id,...,treatments.treatment_duration,treatments.treatment_effect,treatments.treatment_effect_indicator,treatments.treatment_frequency,treatments.treatment_id,treatments.treatment_intent_type,treatments.treatment_or_therapy,treatments.treatment_outcome,treatments.treatment_outcome_duration,treatments.treatment_type
0,TCGA-KIRC,0022478c-4dfd-4cbe-a05e-fb20310844e3,Consent by Death,'--,'--,Adenomas and Adenocarcinomas,Diagnosis,'--,Kidney,TCGA-B0-5088,...,'--,'--,'--,'--,3923cb76-3a32-410e-97a7-c774edbd9469,'--,no,'--,'--,"Radiation Therapy, NOS"
1,TCGA-KIRC,0022478c-4dfd-4cbe-a05e-fb20310844e3,Consent by Death,'--,'--,Adenomas and Adenocarcinomas,Diagnosis,'--,Kidney,TCGA-B0-5088,...,'--,'--,'--,'--,ef66cc4b-62a0-4444-9f2e-dfa838784d23,'--,no,'--,'--,"Pharmaceutical Therapy, NOS"
2,TCGA-KIRC,0022478c-4dfd-4cbe-a05e-fb20310844e3,Consent by Death,'--,'--,Adenomas and Adenocarcinomas,Diagnosis,'--,Kidney,TCGA-B0-5088,...,'--,'--,'--,'--,'--,'--,'--,'--,'--,'--
3,TCGA-KIRC,01277e9d-a35f-45d9-9e60-2e8cd79630a0,Informed Consent,95,'--,Adenomas and Adenocarcinomas,Diagnosis,No,Kidney,TCGA-DV-A4W0,...,'--,'--,'--,'--,7f8fb081-78fc-4fcf-a512-01390357df50,'--,no,'--,'--,"Pharmaceutical Therapy, NOS"
4,TCGA-KIRC,01277e9d-a35f-45d9-9e60-2e8cd79630a0,Informed Consent,95,'--,Adenomas and Adenocarcinomas,Diagnosis,No,Kidney,TCGA-DV-A4W0,...,'--,'--,'--,'--,8bc0c868-1856-487d-9556-dfb0e28141d7,'--,no,'--,'--,"Surgery, NOS"

In [5]:
# Show first 5 rows of follow-up data
print("=== Follow-Up Data (first 5 rows) ===")
follow_up.head()

=== Follow-Up Data (first 5 rows) ===

,project.project_id,cases.case_id,cases.submitter_id,follow_ups.adverse_event,follow_ups.adverse_event_grade,follow_ups.aids_risk_factors,follow_ups.barretts_esophagus_goblet_cells_present,follow_ups.bmi,follow_ups.body_surface_area,follow_ups.cause_of_response,...,other_clinical_attributes.undescended_testis_corrected_age,other_clinical_attributes.undescended_testis_corrected_age_range,other_clinical_attributes.undescended_testis_corrected_laterality,other_clinical_attributes.undescended_testis_corrected_method,other_clinical_attributes.undescended_testis_history,other_clinical_attributes.undescended_testis_history_laterality,other_clinical_attributes.viral_hepatitis_serologies,other_clinical_attributes.viral_hepatitis_serology_tests,other_clinical_attributes.weeks_gestation_at_birth,other_clinical_attributes.weight
0,TCGA-KIRC,0022478c-4dfd-4cbe-a05e-fb20310844e3,TCGA-B0-5088,'--,'--,'--,'--,'--,'--,'--,...,'--,'--,'--,'--,'--,'--,'--,'--,'--,'--
1,TCGA-KIRC,0022478c-4dfd-4cbe-a05e-fb20310844e3,TCGA-B0-5088,'--,'--,'--,'--,'--,'--,'--,...,'--,'--,'--,'--,'--,'--,'--,'--,'--,'--
2,TCGA-KIRC,0022478c-4dfd-4cbe-a05e-fb20310844e3,TCGA-B0-5088,'--,'--,'--,'--,'--,'--,'--,...,'--,'--,'--,'--,'--,'--,'--,'--,'--,'--
3,TCGA-KIRC,0022478c-4dfd-4cbe-a05e-fb20310844e3,TCGA-B0-5088,'--,'--,'--,'--,'--,'--,'--,...,'--,'--,'--,'--,'--,'--,'--,'--,'--,'--
4,TCGA-KIRC,0022478c-4dfd-4cbe-a05e-fb20310844e3,TCGA-B0-5088,'--,'--,'--,'--,'--,'--,'--,...,'--,'--,'--,'--,'--,'--,'--,'--,'--,'--

In [6]:
# Show first 5 rows of expression data
print("=== Expression Data (first 5 rows) ===")
expression.head()

=== Expression Data (first 5 rows) ===

,sample,TCGA-BP-4162-01,TCGA-CJ-5677-11,TCGA-DV-5566-01,TCGA-BP-5191-01,TCGA-BP-5200-01,TCGA-BP-4347-01,TCGA-BP-4770-01,TCGA-B0-5696-11,TCGA-BP-4762-01,...,TCGA-B0-5104-01,TCGA-A3-3313-01,TCGA-B2-5633-01,TCGA-CJ-4872-01,TCGA-CJ-5684-01,TCGA-CJ-4886-01,TCGA-BP-5009-01,TCGA-BP-4969-01,TCGA-CZ-5461-01,TCGA-CW-5587-01
0,ARHGEF10L,10.5030,10.8969,10.7612,10.2063,10.0616,10.0193,8.4364,11.1427,9.9150,...,10.5586,9.5556,10.2652,9.4981,10.2751,9.9525,10.1273,10.8817,10.1949,10.3294
1,HIF3A,5.5283,6.4943,5.7842,5.0063,5.3326,7.6102,6.0422,5.9789,3.7802,...,6.2061,4.8253,5.1680,8.6195,6.2080,6.3116,6.7446,7.8293,6.1788,6.2293
2,RNF17,3.8036,0.0000,0.0000,0.0000,0.0000,0.3386,0.0000,0.0000,0.0000,...,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.6128,0.0000
3,RNF10,11.4379,12.2130,11.5478,12.3439,11.5149,11.4065,12.1963,12.3946,11.3734,...,11.7338,11.7709,11.4968,11.9561,11.7518,11.5698,12.1565,11.3048,11.5168,11.3489
4,RNF11,11.4180,11.8248,11.3190,10.3413,11.2923,10.9971,11.8936,11.7217,12.2329,...,11.7629,10.2373,11.4637,11.4391,11.3992,11.4937,11.4015,10.8842,11.6230,11.5469

In [7]:
# Print all column names in the clinical data
print("=== Clinical Column Names ===")
print(list(clinical.columns))

=== Clinical Column Names ===
['project.project_id', 'cases.case_id', 'cases.consent_type', 'cases.days_to_consent', 'cases.days_to_lost_to_followup', 'cases.disease_type', 'cases.index_date', 'cases.lost_to_followup', 'cases.primary_site', 'cases.submitter_id', 'demographic.age_at_index', 'demographic.age_is_obfuscated', 'demographic.cause_of_death', 'demographic.cause_of_death_source', 'demographic.country_of_birth', 'demographic.country_of_residence_at_enrollment', 'demographic.days_to_birth', 'demographic.days_to_death', 'demographic.demographic_id', 'demographic.education_level', 'demographic.ethnicity', 'demographic.gender', 'demographic.marital_status', 'demographic.occupation_duration_years', 'demographic.population_group', 'demographic.premature_at_birth', 'demographic.race', 'demographic.submitter_id', 'demographic.vital_status', 'demographic.weeks_gestation_at_birth', 'demographic.year_of_birth', 'demographic.year_of_death', 'diagnoses.adrenal_hormone', 'diagnoses.age_at_diagnosis', 'diagnoses.ajcc_clinical_m', 'diagnoses.ajcc_clinical_n', 'diagnoses.ajcc_clinical_stage', 'diagnoses.ajcc_clinical_t', 'diagnoses.ajcc_pathologic_m', 'diagnoses.ajcc_pathologic_n', 'diagnoses.ajcc_pathologic_stage', 'diagnoses.ajcc_pathologic_t', 'diagnoses.ajcc_serum_tumor_markers', 'diagnoses.ajcc_staging_system_edition', 'diagnoses.ann_arbor_b_symptoms', 'diagnoses.ann_arbor_b_symptoms_described', 'diagnoses.ann_arbor_clinical_stage', 'diagnoses.ann_arbor_extranodal_involvement', 'diagnoses.ann_arbor_pathologic_stage', 'diagnoses.best_overall_response', 'diagnoses.burkitt_lymphoma_clinical_variant', 'diagnoses.calgb_risk_group', 'diagnoses.cancer_detection_method', 'diagnoses.child_pugh_classification', 'diagnoses.clark_level', 'diagnoses.classification_of_tumor', 'diagnoses.cog_liver_stage', 'diagnoses.cog_neuroblastoma_risk_group', 'diagnoses.cog_renal_stage', 'diagnoses.cog_rhabdomyosarcoma_risk_group', 'diagnoses.contiguous_organ_invaded', 'diagnoses.days_to_best_overall_response', 'diagnoses.days_to_diagnosis', 'diagnoses.days_to_last_follow_up', 'diagnoses.days_to_last_known_disease_status', 'diagnoses.days_to_recurrence', 'diagnoses.diagnosis_id', 'diagnoses.diagnosis_is_primary_disease', 'diagnoses.double_expressor_lymphoma', 'diagnoses.double_hit_lymphoma', 'diagnoses.eln_risk_classification', 'diagnoses.enneking_msts_grade', 'diagnoses.enneking_msts_metastasis', 'diagnoses.enneking_msts_stage', 'diagnoses.enneking_msts_tumor_site', 'diagnoses.ensat_clinical_m', 'diagnoses.ensat_pathologic_n', 'diagnoses.ensat_pathologic_stage', 'diagnoses.ensat_pathologic_t', 'diagnoses.esophageal_columnar_dysplasia_degree', 'diagnoses.esophageal_columnar_metaplasia_present', 'diagnoses.fab_morphology_code', 'diagnoses.figo_stage', 'diagnoses.figo_staging_edition_year', 'diagnoses.first_symptom_longest_duration', 'diagnoses.first_symptom_prior_to_diagnosis', 'diagnoses.gastric_esophageal_junction_involvement', 'diagnoses.gleason_grade_group', 'diagnoses.gleason_grade_tertiary', 'diagnoses.gleason_patterns_percent', 'diagnoses.gleason_score', 'diagnoses.goblet_cells_columnar_mucosa_present', 'diagnoses.icd_10_code', 'diagnoses.igcccg_stage', 'diagnoses.inpc_grade', 'diagnoses.inpc_histologic_group', 'diagnoses.inrg_stage', 'diagnoses.inss_stage', 'diagnoses.international_prognostic_index', 'diagnoses.irs_group', 'diagnoses.irs_stage', 'diagnoses.ishak_fibrosis_score', 'diagnoses.iss_stage', 'diagnoses.last_known_disease_status', 'diagnoses.laterality', 'diagnoses.margin_distance', 'diagnoses.margins_involved_site', 'diagnoses.masaoka_stage', 'diagnoses.max_tumor_bulk_site', 'diagnoses.medulloblastoma_molecular_classification', 'diagnoses.melanoma_known_primary', 'diagnoses.metastasis_at_diagnosis', 'diagnoses.metastasis_at_diagnosis_site', 'diagnoses.method_of_diagnosis', 'diagnoses.micropapillary_features', 'diagnoses.mitosis_karyorrhexis_index', 'diagnoses.mitotic_count', 'diagnoses.morphology', 'diagnoses.ovarian_specimen_status', 'diagnoses.ovarian_surface_involvement', 'diagnoses.papillary_renal_cell_type', 'diagnoses.pediatric_kidney_staging', 'diagnoses.peritoneal_fluid_cytological_status', 'diagnoses.pregnant_at_diagnosis', 'diagnoses.primary_diagnosis', 'diagnoses.primary_disease', 'diagnoses.primary_gleason_grade', 'diagnoses.prior_malignancy', 'diagnoses.prior_treatment', 'diagnoses.progression_or_recurrence', 'diagnoses.residual_disease', 'diagnoses.satellite_nodule_present', 'diagnoses.secondary_gleason_grade', 'diagnoses.site_of_resection_or_biopsy', 'diagnoses.sites_of_involvement', 'diagnoses.sites_of_involvement_count', 'diagnoses.submitter_id', 'diagnoses.supratentorial_localization', 'diagnoses.synchronous_malignancy', 'diagnoses.tissue_or_organ_of_origin', 'diagnoses.tumor_burden', 'diagnoses.tumor_confined_to_organ_of_origin', 'diagnoses.tumor_depth', 'diagnoses.tumor_focality', 'diagnoses.tumor_grade', 'diagnoses.tumor_grade_category', 'diagnoses.tumor_of_origin', 'diagnoses.tumor_regression_grade', 'diagnoses.uicc_clinical_m', 'diagnoses.uicc_clinical_n', 'diagnoses.uicc_clinical_stage', 'diagnoses.uicc_clinical_t', 'diagnoses.uicc_pathologic_m', 'diagnoses.uicc_pathologic_n', 'diagnoses.uicc_pathologic_stage', 'diagnoses.uicc_pathologic_t', 'diagnoses.uicc_staging_system_edition', 'diagnoses.ulceration_indicator', 'diagnoses.weiss_assessment_findings', 'diagnoses.weiss_assessment_score', 'diagnoses.who_cns_grade', 'diagnoses.who_nte_grade', 'diagnoses.wilms_tumor_histologic_subtype', 'diagnoses.year_of_diagnosis', 'treatments.chemo_concurrent_to_radiation', 'treatments.clinical_trial_indicator', 'treatments.course_number', 'treatments.days_to_treatment_end', 'treatments.days_to_treatment_start', 'treatments.drug_category', 'treatments.embolic_agent', 'treatments.initial_disease_status', 'treatments.lesions_treated_number', 'treatments.margin_distance', 'treatments.margin_status', 'treatments.margins_involved_site', 'treatments.number_of_cycles', 'treatments.number_of_fractions', 'treatments.prescribed_dose', 'treatments.prescribed_dose_units', 'treatments.pretreatment', 'treatments.protocol_identifier', 'treatments.radiosensitizing_agent', 'treatments.reason_treatment_ended', 'treatments.reason_treatment_not_given', 'treatments.regimen_or_line_of_therapy', 'treatments.residual_disease', 'treatments.route_of_administration', 'treatments.submitter_id', 'treatments.therapeutic_agents', 'treatments.therapeutic_level_achieved', 'treatments.therapeutic_levels_achieved', 'treatments.therapeutic_target_level', 'treatments.timepoint_category', 'treatments.treatment_anatomic_site', 'treatments.treatment_anatomic_sites', 'treatments.treatment_arm', 'treatments.treatment_dose', 'treatments.treatment_dose_max', 'treatments.treatment_dose_units', 'treatments.treatment_duration', 'treatments.treatment_effect', 'treatments.treatment_effect_indicator', 'treatments.treatment_frequency', 'treatments.treatment_id', 'treatments.treatment_intent_type', 'treatments.treatment_or_therapy', 'treatments.treatment_outcome', 'treatments.treatment_outcome_duration', 'treatments.treatment_type']

In [8]:
# Print all column names in the follow-up data
print("=== Follow-Up Column Names ===")
print(list(follow_up.columns))

=== Follow-Up Column Names ===
['project.project_id', 'cases.case_id', 'cases.submitter_id', 'follow_ups.adverse_event', 'follow_ups.adverse_event_grade', 'follow_ups.aids_risk_factors', 'follow_ups.barretts_esophagus_goblet_cells_present', 'follow_ups.bmi', 'follow_ups.body_surface_area', 'follow_ups.cause_of_response', 'follow_ups.cd4_count', 'follow_ups.cdc_hiv_risk_factors', 'follow_ups.comorbidities', 'follow_ups.comorbidity', 'follow_ups.comorbidity_method_of_diagnosis', 'follow_ups.days_to_adverse_event', 'follow_ups.days_to_comorbidity', 'follow_ups.days_to_first_event', 'follow_ups.days_to_follow_up', 'follow_ups.days_to_imaging', 'follow_ups.days_to_progression', 'follow_ups.days_to_progression_free', 'follow_ups.days_to_recurrence', 'follow_ups.days_to_risk_factor', 'follow_ups.diabetes_treatment_type', 'follow_ups.discontiguous_lesion_count', 'follow_ups.disease_response', 'follow_ups.dlco_ref_predictive_percent', 'follow_ups.ecog_performance_status', 'follow_ups.evidence_of_progression_type', 'follow_ups.evidence_of_recurrence_type', 'follow_ups.eye_color', 'follow_ups.fev1_fvc_post_bronch_percent', 'follow_ups.fev1_fvc_pre_bronch_percent', 'follow_ups.fev1_ref_post_bronch_percent', 'follow_ups.fev1_ref_pre_bronch_percent', 'follow_ups.first_event', 'follow_ups.follow_up_id', 'follow_ups.haart_treatment_indicator', 'follow_ups.height', 'follow_ups.hepatitis_sustained_virological_response', 'follow_ups.histologic_progression', 'follow_ups.history_of_tumor', 'follow_ups.history_of_tumor_type', 'follow_ups.hiv_viral_load', 'follow_ups.hormonal_contraceptive_type', 'follow_ups.hormonal_contraceptive_use', 'follow_ups.hormone_replacement_therapy_type', 'follow_ups.hpv_positive_type', 'follow_ups.hysterectomy_margins_involved', 'follow_ups.hysterectomy_type', 'follow_ups.imaging_anatomic_site', 'follow_ups.imaging_findings', 'follow_ups.imaging_result', 'follow_ups.imaging_suv', 'follow_ups.imaging_suv_max', 'follow_ups.imaging_type', 'follow_ups.immunosuppressive_treatment_type', 'follow_ups.karnofsky_performance_status', 'follow_ups.menopause_status', 'follow_ups.nadir_cd4_count', 'follow_ups.pancreatitis_onset_year', 'follow_ups.peritoneal_washing_results', 'follow_ups.pregnancy_count', 'follow_ups.pregnancy_outcome', 'follow_ups.procedures_performed', 'follow_ups.progression_or_recurrence', 'follow_ups.progression_or_recurrence_anatomic_site', 'follow_ups.progression_or_recurrence_type', 'follow_ups.recist_targeted_regions_number', 'follow_ups.recist_targeted_regions_sum', 'follow_ups.reflux_treatment_type', 'follow_ups.risk_factor', 'follow_ups.risk_factor_method_of_diagnosis', 'follow_ups.risk_factor_treatment', 'follow_ups.risk_factors', 'follow_ups.scan_tracer_used', 'follow_ups.submitter_id', 'follow_ups.timepoint_category', 'follow_ups.treatment_emergent_adverse_event', 'follow_ups.undescended_testis_corrected', 'follow_ups.undescended_testis_corrected_age', 'follow_ups.undescended_testis_corrected_laterality', 'follow_ups.undescended_testis_corrected_method', 'follow_ups.undescended_testis_history', 'follow_ups.undescended_testis_history_laterality', 'follow_ups.viral_hepatitis_serologies', 'follow_ups.weight', 'follow_ups.year_of_follow_up', 'molecular_tests.aa_change', 'molecular_tests.aneuploidy', 'molecular_tests.antigen', 'molecular_tests.biospecimen_type', 'molecular_tests.biospecimen_volume', 'molecular_tests.blood_test_normal_range_lower', 'molecular_tests.blood_test_normal_range_upper', 'molecular_tests.cell_count', 'molecular_tests.chromosomal_translocation', 'molecular_tests.chromosome', 'molecular_tests.chromosome_arm', 'molecular_tests.clonality', 'molecular_tests.copy_number', 'molecular_tests.cytoband', 'molecular_tests.days_to_test', 'molecular_tests.exon', 'molecular_tests.gene_symbol', 'molecular_tests.histone_family', 'molecular_tests.histone_variant', 'molecular_tests.hpv_strain', 'molecular_tests.intron', 'molecular_tests.laboratory_test', 'molecular_tests.loci_abnormal_count', 'molecular_tests.loci_count', 'molecular_tests.locus', 'molecular_tests.mismatch_repair_mutation', 'molecular_tests.mitotic_count', 'molecular_tests.mitotic_total_area', 'molecular_tests.molecular_analysis_method', 'molecular_tests.molecular_consequence', 'molecular_tests.molecular_test_id', 'molecular_tests.mutation_codon', 'molecular_tests.pathogenicity', 'molecular_tests.ploidy', 'molecular_tests.second_exon', 'molecular_tests.second_gene_symbol', 'molecular_tests.specialized_molecular_test', 'molecular_tests.staining_intensity_scale', 'molecular_tests.staining_intensity_value', 'molecular_tests.submitter_id', 'molecular_tests.test_analyte_type', 'molecular_tests.test_result', 'molecular_tests.test_units', 'molecular_tests.test_value', 'molecular_tests.test_value_range', 'molecular_tests.timepoint_category', 'molecular_tests.transcript', 'molecular_tests.variant_origin', 'molecular_tests.variant_type', 'molecular_tests.zygosity', 'other_clinical_attributes.aids_risk_factors', 'other_clinical_attributes.bmi', 'other_clinical_attributes.body_surface_area', 'other_clinical_attributes.cd4_count', 'other_clinical_attributes.cdc_hiv_risk_factors', 'other_clinical_attributes.comorbidities', 'other_clinical_attributes.comorbidity_method_of_diagnosis', 'other_clinical_attributes.days_to_comorbidity', 'other_clinical_attributes.days_to_risk_factor', 'other_clinical_attributes.diabetes_treatment_type', 'other_clinical_attributes.dlco_ref_predictive_percent', 'other_clinical_attributes.exercise_frequency_weekly', 'other_clinical_attributes.eye_color', 'other_clinical_attributes.fev1_fvc_post_bronch_percent', 'other_clinical_attributes.fev1_fvc_pre_bronch_percent', 'other_clinical_attributes.fev1_ref_post_bronch_percent', 'other_clinical_attributes.fev1_ref_pre_bronch_percent', 'other_clinical_attributes.haart_treatment_indicator', 'other_clinical_attributes.height', 'other_clinical_attributes.hepatitis_sustained_virological_response', 'other_clinical_attributes.hiv_viral_load', 'other_clinical_attributes.hormonal_contraceptive_type', 'other_clinical_attributes.hormonal_contraceptive_use', 'other_clinical_attributes.hormonal_replacement_therapy_status', 'other_clinical_attributes.hormone_replacement_therapy_type', 'other_clinical_attributes.hysterectomy_margins_involved', 'other_clinical_attributes.hysterectomy_type', 'other_clinical_attributes.immunosuppressive_treatment_type', 'other_clinical_attributes.menopause_status', 'other_clinical_attributes.myasthenia_gravis_classification', 'other_clinical_attributes.nadir_cd4_count', 'other_clinical_attributes.nononcologic_therapeutic_agents', 'other_clinical_attributes.number_of_pregnancies', 'other_clinical_attributes.other_clinical_attribute_id', 'other_clinical_attributes.oxygen_use_indicator', 'other_clinical_attributes.oxygen_use_type', 'other_clinical_attributes.pancreatitis_onset_year', 'other_clinical_attributes.pregnancy_count', 'other_clinical_attributes.pregnancy_outcome', 'other_clinical_attributes.pregnant_at_diagnosis', 'other_clinical_attributes.premature_at_birth', 'other_clinical_attributes.reflux_treatment_type', 'other_clinical_attributes.risk_factor_method_of_diagnosis', 'other_clinical_attributes.risk_factor_treatment', 'other_clinical_attributes.risk_factors', 'other_clinical_attributes.submitter_id', 'other_clinical_attributes.timepoint_category', 'other_clinical_attributes.treatment_frequency', 'other_clinical_attributes.undescended_testis_corrected', 'other_clinical_attributes.undescended_testis_corrected_age', 'other_clinical_attributes.undescended_testis_corrected_age_range', 'other_clinical_attributes.undescended_testis_corrected_laterality', 'other_clinical_attributes.undescended_testis_corrected_method', 'other_clinical_attributes.undescended_testis_history', 'other_clinical_attributes.undescended_testis_history_laterality', 'other_clinical_attributes.viral_hepatitis_serologies', 'other_clinical_attributes.viral_hepatitis_serology_tests', 'other_clinical_attributes.weeks_gestation_at_birth', 'other_clinical_attributes.weight']

In [9]:
# Print the first 10 column names of expression data
# Expression data usually has thousands of gene columns, so we just peek at the first 10
print("=== Expression Data — First 10 Columns ===")
print(list(expression.columns[:10]))

=== Expression Data — First 10 Columns ===
['sample', 'TCGA-BP-4162-01', 'TCGA-CJ-5677-11', 'TCGA-DV-5566-01', 'TCGA-BP-5191-01', 'TCGA-BP-5200-01', 'TCGA-BP-4347-01', 'TCGA-BP-4770-01', 'TCGA-B0-5696-11', 'TCGA-BP-4762-01']

# Step 2: Identify Patient ID Columns
We need to find columns that contain patient identifiers so we can later link clinical, follow-up, and expression data.

In [10]:
# Find columns in clinical data that look like patient IDs
# We search for columns containing "id", "case", "patient", or "submitter"
id_keywords = ["id", "case", "patient", "submitter", "barcode"]

print("=== Clinical columns that may contain patient IDs ===")
for col in clinical.columns:
    if any(kw in col.lower() for kw in id_keywords):
        print(f"  {col}")

print()
print("=== Follow-Up columns that may contain patient IDs ===")
for col in follow_up.columns:
    if any(kw in col.lower() for kw in id_keywords):
        print(f"  {col}")

=== Clinical columns that may contain patient IDs ===
  project.project_id
  cases.case_id
  cases.consent_type
  cases.days_to_consent
  cases.days_to_lost_to_followup
  cases.disease_type
  cases.index_date
  cases.lost_to_followup
  cases.primary_site
  cases.submitter_id
  demographic.country_of_residence_at_enrollment
  demographic.demographic_id
  demographic.submitter_id
  diagnoses.diagnosis_id
  diagnoses.pediatric_kidney_staging
  diagnoses.peritoneal_fluid_cytological_status
  diagnoses.residual_disease
  diagnoses.submitter_id
  treatments.protocol_identifier
  treatments.residual_disease
  treatments.submitter_id
  treatments.treatment_id

=== Follow-Up columns that may contain patient IDs ===
  project.project_id
  cases.case_id
  cases.submitter_id
  follow_ups.aids_risk_factors
  follow_ups.comorbidities
  follow_ups.comorbidity
  follow_ups.comorbidity_method_of_diagnosis
  follow_ups.days_to_comorbidity
  follow_ups.evidence_of_progression_type
  follow_ups.evidence_of_recurrence_type
  follow_ups.follow_up_id
  follow_ups.submitter_id
  molecular_tests.aneuploidy
  molecular_tests.molecular_test_id
  molecular_tests.ploidy
  molecular_tests.submitter_id
  other_clinical_attributes.aids_risk_factors
  other_clinical_attributes.comorbidities
  other_clinical_attributes.comorbidity_method_of_diagnosis
  other_clinical_attributes.days_to_comorbidity
  other_clinical_attributes.other_clinical_attribute_id
  other_clinical_attributes.submitter_id

In [11]:
# Show 5 example values from the likely ID columns in clinical data
# "case_submitter_id" is the typical TCGA patient ID column (format: TCGA-XX-XXXX)
print("=== Clinical — sample ID values (first 5) ===")
for col in clinical.columns:
    if any(kw in col.lower() for kw in ["submitter_id", "case_id", "patient"]):
        print(f"\n  {col}:")
        print(f"  {clinical[col].head().tolist()}")

=== Clinical — sample ID values (first 5) ===

  cases.case_id:
  ['0022478c-4dfd-4cbe-a05e-fb20310844e3', '0022478c-4dfd-4cbe-a05e-fb20310844e3', '0022478c-4dfd-4cbe-a05e-fb20310844e3', '01277e9d-a35f-45d9-9e60-2e8cd79630a0', '01277e9d-a35f-45d9-9e60-2e8cd79630a0']

  cases.submitter_id:
  ['TCGA-B0-5088', 'TCGA-B0-5088', 'TCGA-B0-5088', 'TCGA-DV-A4W0', 'TCGA-DV-A4W0']

  demographic.submitter_id:
  ['TCGA-B0-5088_demographic', 'TCGA-B0-5088_demographic', 'TCGA-B0-5088_demographic', 'TCGA-DV-A4W0_demographic', 'TCGA-DV-A4W0_demographic']

  diagnoses.submitter_id:
  ['TCGA-B0-5088_diagnosis2', 'TCGA-B0-5088_diagnosis2', 'TCGA-B0-5088_diagnosis', 'TCGA-DV-A4W0_diagnosis2', 'TCGA-DV-A4W0_diagnosis2']

  treatments.submitter_id:
  ['TCGA-B0-5088_treatment2', 'TCGA-B0-5088_treatment', "'--", 'TCGA-DV-A4W0_treatment6', 'TCGA-DV-A4W0_treatment8']

In [12]:
# Show 5 example values from the likely ID columns in follow-up data
print("=== Follow-Up — sample ID values (first 5) ===")
for col in follow_up.columns:
    if any(kw in col.lower() for kw in ["submitter_id", "case_id", "patient"]):
        print(f"\n  {col}:")
        print(f"  {follow_up[col].head().tolist()}")

=== Follow-Up — sample ID values (first 5) ===

  cases.case_id:
  ['0022478c-4dfd-4cbe-a05e-fb20310844e3', '0022478c-4dfd-4cbe-a05e-fb20310844e3', '0022478c-4dfd-4cbe-a05e-fb20310844e3', '0022478c-4dfd-4cbe-a05e-fb20310844e3', '0022478c-4dfd-4cbe-a05e-fb20310844e3']

  cases.submitter_id:
  ['TCGA-B0-5088', 'TCGA-B0-5088', 'TCGA-B0-5088', 'TCGA-B0-5088', 'TCGA-B0-5088']

  follow_ups.submitter_id:
  ['TCGA-B0-5088_follow_up2', 'TCGA-B0-5088_follow_up', "'--", "'--", "'--"]

  molecular_tests.submitter_id:
  ["'--", "'--", 'TCGA-B0-5088_molecular_test4', 'TCGA-B0-5088_molecular_test3', 'TCGA-B0-5088_molecular_test2']

  other_clinical_attributes.submitter_id:
  ["'--", "'--", "'--", "'--", "'--"]

In [13]:
# Inspect expression data column names
# Expression columns are usually sample barcodes like TCGA-XX-XXXX-01
# The first column might be a gene name/ID column

print("=== Expression Data — first 5 column names ===")
print(expression.columns[:5].tolist())

print("\n=== Expression Data — last 5 column names ===")
print(expression.columns[-5:].tolist())

print(f"\nTotal columns in expression data: {len(expression.columns)}")

=== Expression Data — first 5 column names ===
['sample', 'TCGA-BP-4162-01', 'TCGA-CJ-5677-11', 'TCGA-DV-5566-01', 'TCGA-BP-5191-01']

=== Expression Data — last 5 column names ===
['TCGA-CJ-4886-01', 'TCGA-BP-5009-01', 'TCGA-BP-4969-01', 'TCGA-CZ-5461-01', 'TCGA-CW-5587-01']

Total columns in expression data: 607

In [14]:
# Extract patient IDs from expression column names
# TCGA barcodes look like: TCGA-XX-XXXX-01A
# The patient ID is the first 3 parts: TCGA-XX-XXXX
# We remove the sample portion (-01, -11, etc.) by keeping only the first 12 characters
# or by splitting on "-" and joining the first 3 parts

# Get columns that look like TCGA barcodes (skip the gene name column)
tcga_columns = [col for col in expression.columns if col.startswith("TCGA")]

print(f"Number of TCGA sample columns: {len(tcga_columns)}")
print(f"\nExample full barcodes (first 5):")
print(tcga_columns[:5])

# Extract patient ID by keeping first 3 parts: TCGA-XX-XXXX
expression_patient_ids = ["-".join(col.split("-")[:3]) for col in tcga_columns]

print(f"\nExtracted patient IDs (first 5):")
print(expression_patient_ids[:5])

Number of TCGA sample columns: 606

Example full barcodes (first 5):
['TCGA-BP-4162-01', 'TCGA-CJ-5677-11', 'TCGA-DV-5566-01', 'TCGA-BP-5191-01', 'TCGA-BP-5200-01']

Extracted patient IDs (first 5):
['TCGA-BP-4162', 'TCGA-CJ-5677', 'TCGA-DV-5566', 'TCGA-BP-5191', 'TCGA-BP-5200']

In [15]:
# Count unique patients in each dataset
# This helps us understand how many patients overlap across datasets

# Clinical: use case_submitter_id (adjust if your column name is different)
id_col_clinical = [c for c in clinical.columns if "submitter_id" in c.lower()][0]
clinical_ids = clinical[id_col_clinical].nunique()

# Follow-up: use the submitter_id column
id_col_followup = [c for c in follow_up.columns if "submitter_id" in c.lower()][0]
followup_ids = follow_up[id_col_followup].nunique()

# Expression: unique patient IDs we extracted above
expr_ids = len(set(expression_patient_ids))

print("=== Unique Patient Counts ===")
print(f"  Clinical ({id_col_clinical}):    {clinical_ids}")
print(f"  Follow-Up ({id_col_followup}):   {followup_ids}")
print(f"  Expression (from barcodes):       {expr_ids}")

=== Unique Patient Counts ===
  Clinical (cases.submitter_id):    537
  Follow-Up (cases.submitter_id):   537
  Expression (from barcodes):       533

# Step 3: Filter Expression Data — Keep Tumor Samples Only
In TCGA, sample barcodes end with a sample type code:
- **-01** = Primary Tumor
- **-11** = Solid Tissue Normal

For survival analysis we only need tumor samples, so we drop the normal (-11) columns.

In [16]:
# Count how many columns are tumor (-01) vs normal (-11) vs other
# The last 3 characters of a TCGA barcode column indicate sample type

tumor_cols  = [col for col in tcga_columns if col.endswith("-01")]
normal_cols = [col for col in tcga_columns if col.endswith("-11")]
other_cols  = [col for col in tcga_columns if not col.endswith("-01") and not col.endswith("-11")]

print(f"Tumor samples  (-01): {len(tumor_cols)}")
print(f"Normal samples (-11): {len(normal_cols)}")
print(f"Other samples:        {len(other_cols)}")

# Show a few examples of each type
print(f"\nExample tumor columns:  {tumor_cols[:3]}")
print(f"Example normal columns: {normal_cols[:3]}")

Tumor samples  (-01): 533
Normal samples (-11): 72
Other samples:        1

Example tumor columns:  ['TCGA-BP-4162-01', 'TCGA-DV-5566-01', 'TCGA-BP-5191-01']
Example normal columns: ['TCGA-CJ-5677-11', 'TCGA-B0-5696-11', 'TCGA-CJ-5679-11']

In [17]:
# Build the filtered expression dataframe
# WHY tumor only? In survival analysis we want to link each patient's
# tumor gene expression to their survival outcome. Normal tissue samples
# don't reflect the tumor biology driving patient outcomes.

# Step 1: Identify the gene name column (the first non-TCGA column)
gene_col = [col for col in expression.columns if not col.startswith("TCGA")]
print(f"Gene name column(s): {gene_col}")

# Step 2: Keep gene column + tumor sample columns only
cols_to_keep = gene_col + tumor_cols
expression_tumor = expression[cols_to_keep]

print(f"\nOriginal expression shape:  {expression.shape}")
print(f"Filtered expression shape:  {expression_tumor.shape}")
print(f"  (rows = genes, columns = 1 gene-name col + {len(tumor_cols)} tumor samples)")

Gene name column(s): ['sample']

Original expression shape:  (20530, 607)
Filtered expression shape:  (20530, 534)
  (rows = genes, columns = 1 gene-name col + 533 tumor samples)

In [18]:
# Quick sanity check — preview the filtered data
print("=== Filtered Expression Data (first 5 rows, first 5 columns) ===")
expression_tumor.iloc[:5, :5]

=== Filtered Expression Data (first 5 rows, first 5 columns) ===

,sample,TCGA-BP-4162-01,TCGA-DV-5566-01,TCGA-BP-5191-01,TCGA-BP-5200-01
0,ARHGEF10L,10.5030,10.7612,10.2063,10.0616
1,HIF3A,5.5283,5.7842,5.0063,5.3326
2,RNF17,3.8036,0.0000,0.0000,0.0000
3,RNF10,11.4379,11.5478,12.3439,11.5149
4,RNF11,11.4180,11.3190,10.3413,11.2923

# Step 4: Reshape Expression Data — Samples as Rows
Right now each **column** is a sample and each **row** is a gene.
We transpose so each **row** becomes a sample and each **column** becomes a gene.
This is the standard layout for machine learning (one row per patient).

In [19]:
# Set the gene name column as the index so gene names become column headers after transpose
# gene_col[0] is the name of the gene column we identified earlier (e.g. "gene_id" or "gene_name")

expression_tumor = expression_tumor.set_index(gene_col[0])

# Transpose: rows ↔ columns
# Before: rows=genes, columns=samples  →  After: rows=samples, columns=genes
expr_transposed = expression_tumor.T

print(f"Before transpose: {expression_tumor.shape}  (genes × samples)")
print(f"After transpose:  {expr_transposed.shape}  (samples × genes)")
print(f"\nFirst 3 rows × first 5 columns:")
expr_transposed.iloc[:3, :5]

Before transpose: (20530, 533)  (genes × samples)
After transpose:  (533, 20530)  (samples × genes)

First 3 rows × first 5 columns:

sample           ARHGEF10L   HIF3A   RNF17    RNF10    RNF11
TCGA-BP-4162-01    10.5030  5.5283  3.8036  11.4379  11.4180
TCGA-DV-5566-01    10.7612  5.7842  0.0000  11.5478  11.3190
TCGA-BP-5191-01    10.2063  5.0063  0.0000  12.3439  10.3413

In [20]:
# Create a "sample_id" column from the index
# After transpose, the index holds the original column names (TCGA barcodes like TCGA-XX-XXXX-01)
expr_transposed = expr_transposed.reset_index()
expr_transposed = expr_transposed.rename(columns={"index": "sample_id"})

print("sample_id column — first 5 values:")
print(expr_transposed["sample_id"].head().tolist())

sample_id column — first 5 values:
['TCGA-BP-4162-01', 'TCGA-DV-5566-01', 'TCGA-BP-5191-01', 'TCGA-BP-5200-01', 'TCGA-BP-4347-01']

In [21]:
# Extract patient_id from sample_id
# sample_id looks like: TCGA-XX-XXXX-01
# patient_id is the first 3 parts: TCGA-XX-XXXX (split on "-" and keep first 3)
# This lets us match expression data to clinical/follow-up data later

expr_transposed["patient_id"] = expr_transposed["sample_id"].apply(
    lambda x: "-".join(x.split("-")[:3])
)

print("sample_id vs patient_id — first 5 rows:")
print(expr_transposed[["sample_id", "patient_id"]].head().to_string(index=False))

sample_id vs patient_id — first 5 rows:
      sample_id   patient_id
TCGA-BP-4162-01 TCGA-BP-4162
TCGA-DV-5566-01 TCGA-DV-5566
TCGA-BP-5191-01 TCGA-BP-5191
TCGA-BP-5200-01 TCGA-BP-5200
TCGA-BP-4347-01 TCGA-BP-4347

In [ ]:
# Final shape summary
print("=== Reshaped Expression Data ===")
print(f"Shape: {expr_transposed.shape}")
print(f"  → {expr_transposed.shape[0]} samples (rows)")
print(f"  → {expr_transposed.shape[1]} columns (sample_id + patient_id + {expr_transposed.shape[1] - 2} genes)")
print(f"\nFirst 5 columns: {expr_transposed.columns[:5].tolist()}")
print(f"Last 5 columns:  {expr_transposed.columns[-5:].tolist()}")